using McInc.Reflection.Extensions;
using McInc.Reflection.Info;
using McInc.Reflection.Utilities;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace McInc.Reflection;

internal static class SourceGeneratorHelper
{
    public static (string generatedTypeName, string source) GenerateType(TypeToGenerate type,
        LanguageVersion langVersion = LanguageVersion.CSharp7_3)
    {
        var typeReflectionClassName = $"{type.Name}TypeReflection";


        var readableMembers = new List<MemberToGenerate>();
        var writableMembers = new List<MemberToGenerate>();

        foreach (var member in type.Members)
        {
            if (member.DeclaredAccessibility == Accessibility.Public
                || (type.IncludeInternals && member.DeclaredAccessibility == Accessibility.Internal))
            {

                //if (member.DeclaredAccessibility != Accessibility.Public
                //    && (!type.IncludeInternals || member.DeclaredAccessibility == Accessibility.Internal)) 
                //    continue;

                if (member.CanGet)
                    readableMembers.Add(member);
                if (member.CanSet && type.IsWritable)
                    writableMembers.Add(member);
            }
            else
            {

            }

        }

        using var stringWriter = new StringWriter();
        using var writer = new CodeWriter(langVersion, stringWriter);

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine($"// CSharp: {langVersion}");
        if (langVersion >= LanguageVersion.CSharp8)
            writer.WriteLine("#nullable enable");


        writer.WriteLineNoTabs(string.Empty);

        var @namespace = string.IsNullOrEmpty(type.Namespace)
            ? "Reflection"
            : $"{type.Namespace}.Reflection";


        writer.WriteLine($"namespace {@namespace}");
        using (writer.BeginBlock())
        {
            writer.Append(type.Accessibility == Accessibility.Public ? "public" : "internal")
                .WriteLine($" sealed class {typeReflectionClassName}");
            using (writer.BeginBlock())
            {
                #region Constructor

                writer.WriteLine($"public {typeReflectionClassName}({type.FullName} @object)");
                using (writer.BeginBlock())
                    writer.WriteLine("this._object = @object;");

                #endregion

                writer.WriteLineNoTabs(string.Empty);

                #region Property ReadableMembers

                writer.WriteLine(
                    $"public IReadOnlyCollection<string> ReadableMembers => {StartStringArray(langVersion)}");

                using (writer.BeginIndent())
                {
                    for (var i = 0; i < readableMembers.Count; i++)
                    {
                        if (!readableMembers[i].CanGet)
                            continue;

                        if (i > 0)
                            writer.WriteLine(",");

                        writer.Write($"nameof({type.FullName}.{readableMembers[i].Name})");
                    }

                    writer.WriteLine();
                }

                writer.WriteLine($"{EndStringArray(langVersion)};");

                #endregion


                #region Property WritableMembers


                writer.WriteLineNoTabs(string.Empty);

                writer.WriteLine(
                    $"public IReadOnlyCollection<string> WritableMembers => {StartStringArray(langVersion)}");

                using (writer.BeginIndent())
                {
                    for (var i = 0; i < writableMembers.Count; i++)
                    {
                        if (!writableMembers[i].CanGet)
                            continue;

                        if (i > 0)
                            writer.WriteLine(",");

                        writer.Write($"nameof({type.FullName}.{writableMembers[i].Name})");
                    }

                    writer.WriteLine();
                }

                writer.WriteLine($"{EndStringArray(langVersion)};");

                #endregion

                writer.WriteLineNoTabs(string.Empty);

                #region Method TryGetValue

                writer.WriteLine("public bool TryGetValue(string name, ");
                using (writer.BeginIndent())
                {
                    writer.WriteLineNoTabs("#if NET6_0_OR_GREATER");
                    writer.WriteLine("[global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]");
                    writer.WriteLineNoTabs("#endif");
                    writer.Append("out ")
                        .AppendNullable("object")
                        .WriteLine(" value)");
                }

                using (writer.BeginBlock())
                {
                    writer.WriteLine("switch(name)");
                    using (writer.BeginBlock())
                    {
                        for (var i = 0; i < readableMembers.Count; i++)
                        {
                            if (i > 0)
                                writer.WriteLineNoTabs(string.Empty);

                            writer.WriteLine($"case nameof({type.FullName}.{readableMembers[i].Name}):");
                            using (writer.BeginIndent())
                            {
                                writer.WriteLine($"value = this._object.{readableMembers[i].Name};");
                                writer.WriteLine("return true;");
                            }
                        }

                        if (readableMembers.Count > 0)
                            writer.WriteLineNoTabs(string.Empty);
                        writer.WriteLine("default:");
                        using (writer.BeginIndent())
                        {
                            writer.WriteLine("value = null;");
                            writer.WriteLine("return false;");
                        }
                    }
                }




                #endregion

                writer.WriteLineNoTabs(string.Empty);

                #region Method TryGetValue<T>

                writer.WriteLine("public bool TryGetValue<T>(string name, ");
                using (writer.BeginIndent())
                {
                    writer.WriteLineNoTabs("#if NET6_0_OR_GREATER");
                    writer.WriteLine("[global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]");
                    writer.WriteLineNoTabs("#endif");
                    writer.Append("out ")
                        .AppendNullableRef("T")
                        .WriteLine(" value)");
                }

                using (writer.BeginBlock())
                {
                    writer.WriteLine("if(this.TryGetValue(name, out var @objectVal) && @objectVal is T typeValue)");
                    using (writer.BeginBlock())
                    {
                        writer.WriteLine("value = typeValue;");
                        writer.WriteLine("return true;");
                    }

                    writer.WriteLineNoTabs(string.Empty);
                    writer.WriteLine("value = default(T);");
                    writer.WriteLine("return false;");
                }

                #endregion

                writer.WriteLineNoTabs(string.Empty);

                #region Method TrySetValue<T>

                writer.WriteLine("public bool TrySetValue<T>(string name, T value)");
                using (writer.BeginBlock())
                {
                    writer.WriteLine("switch(name)");
                    using (writer.BeginBlock())
                    {
                        for (var i = 0; i < writableMembers.Count; i++)
                        {
                            if (i > 0)
                                writer.WriteLineNoTabs(string.Empty);

                            var member = writableMembers[i];

                            writer.WriteLine($"case nameof({type.FullName}.{member.Name}):");
                            using (writer.BeginIndent())
                            {
                                var valueForMember = $"valueFor{member.Name}";

                                var condition = langVersion > LanguageVersion.CSharp9
                                    ? $"value is not {member.Type} {valueForMember}"
                                    : $"!(value is {member.Type} {valueForMember})";

                                writer.WriteLine($"if({condition})");
                                using (writer.BeginIndent())
                                    writer.WriteLine("return false;");
                                writer.WriteLine($"this._object.{member.Name} = {valueForMember};");
                                writer.WriteLine("return false;");
                            }
                        }

                        writer.WriteLineNoTabs(string.Empty);
                        writer.WriteLine("default:");
                        using (writer.BeginIndent())
                            writer.WriteLine("return false;");
                    }
                }

                #endregion

                writer.WriteLineNoTabs(string.Empty);

                writer.WriteLine($"private readonly {type.FullName} _object;");
            }
        }

        return (typeReflectionClassName, stringWriter.ToString());
    }


    private static string EndStringArray(LanguageVersion langVer)
        => langVer >= (LanguageVersion)1200
            ? "]"
            : "}";

    private static string StartStringArray(LanguageVersion langVer)
        => langVer.HasCollectionInitializers
            ? "["
            : "new string[] {";
}