//HintName: SelfIdTypeReflection.g.cs
// <auto-generated />
// CSharp: CSharp10
#nullable enable

namespace Test12345.Reflection
{
   public sealed class SelfIdTypeReflection
   {
      public SelfIdTypeReflection(Test12345.SelfId @object)
      {
         this._object = @object;
      }

      public IReadOnlyCollection<string> ReadableMembers => new string[] {
         nameof(Test12345.SelfId.Id),
         nameof(Test12345.SelfId.Id3),
         nameof(Test12345.SelfId.A),
         nameof(Test12345.SelfId.B),
         nameof(Test12345.SelfId.D),
         nameof(Test12345.SelfId.Gatto)
      };

      public IReadOnlyCollection<string> WritableMembers => new string[] {
         nameof(Test12345.SelfId.Id),
         nameof(Test12345.SelfId.A),
         nameof(Test12345.SelfId.Gatto)
      };

      public bool TryGetValue(string name, 
#if NET6_0_OR_GREATER
         [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
#endif
         out object? value)
      {
         switch(name)
         {
            case nameof(Test12345.SelfId.Id):
               value = this._object.Id;
               return true;

            case nameof(Test12345.SelfId.Id3):
               value = this._object.Id3;
               return true;

            case nameof(Test12345.SelfId.A):
               value = this._object.A;
               return true;

            case nameof(Test12345.SelfId.B):
               value = this._object.B;
               return true;

            case nameof(Test12345.SelfId.D):
               value = this._object.D;
               return true;

            case nameof(Test12345.SelfId.Gatto):
               value = this._object.Gatto;
               return true;

            default:
               value = null;
               return false;
         }
      }

      public bool TryGetValue<T>(string name, 
#if NET6_0_OR_GREATER
         [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
#endif
         out T? value)
      {
         if(this.TryGetValue(name, out var @objectVal) && @objectVal is T typeValue)
         {
            value = typeValue;
            return true;
         }

         value = default(T);
         return false;
      }

      public bool TrySetValue<T>(string name, T value)
      {
         switch(name)
         {
            case nameof(Test12345.SelfId.Id):
               if(value is not int valueForId)
                  return false;
               this._object.Id = valueForId;
               return false;

            case nameof(Test12345.SelfId.A):
               if(value is not int valueForA)
                  return false;
               this._object.A = valueForA;
               return false;

            case nameof(Test12345.SelfId.C):
               if(value is not int valueForC)
                  return false;
               this._object.C = valueForC;
               return false;

            case nameof(Test12345.SelfId.Gatto):
               if(value is not string valueForGatto)
                  return false;
               this._object.Gatto = valueForGatto;
               return false;

            default:
               return false;
         }
      }

      private readonly Test12345.SelfId _object;
   }
}
