//HintName: SelfIdTypeReflection.g.cs
// <auto-generated />
// CSharp: CSharp10
#nullable enable

namespace Test12345.Reflection
{
    public sealed class SelfIdTypeReflection
    {
        public SelfIdTypeReflection(Test12345.SelfId @object)
        {
            this._object = @object;
        }

        public IReadOnlyCollection<string> ReadableMembers => new string[] {
            nameof(Test12345.SelfId.Gatto2)
        };

        public IReadOnlyCollection<string> WritableMembers => new string[] {
            nameof(Test12345.SelfId.Gatto2)
        };

        public bool TryGetValue(string name,
#if NET6_0_OR_GREATER
            [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
#endif
            out object? value)
        {
            switch (name)
            {
                case nameof(Test12345.SelfId.Gatto2):
                    value = this._object.Gatto2;
                    return true;

                default:
                    value = null;
                    return false;
            }
        }

        public bool TryGetValue<T>(string name,
#if NET6_0_OR_GREATER
            [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]
#endif
            out T? value)
        {
            if (this.TryGetValue(name, out var @objectVal) && @objectVal is T typeValue)
            {
                value = typeValue;
                return true;
            }

            value = default(T);
            return false;
        }

        public bool TrySetValue<T>(string name, T value)
        {
            switch (name)
            {
                case nameof(Test12345.SelfId.Gatto2):
                    if (value is not string valueForGatto2)
                        return false;
                    this._object.Gatto2 = valueForGatto2;
                    return false;

                default:
                    return false;
            }
        }

        private readonly Test12345.SelfId _object;
    }
}