<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <AssemblyName>McInc.Reflection.Abstractions</AssemblyName>
	  <RootNamespace>McInc.Reflection</RootNamespace>

	  <!--<TargetFrameworks>netstandard2.0; net6.0;</TargetFrameworks>-->
	  <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

</Project>
